### ISSUE TITLE
Why you got downvoted on reddit

### ISSUE THREAD

**Issue by eorroe** [GandalfTheHobbit/domLib#1]
Disclaimer: I never downvote on reddit

But the reason you got downvoted is because you didn't show in your README how to use the library

but ayy checkout my DOM library: https://github.com/eorroe/NodeList.js

**Comment by GandalfTheHobbit** [comment]
In my README I put a link to the documentation and said "You can learn more in the documentation, which is in the wiki", which gives all the information

**Comment by eorroe** [comment]
On github repos most just scroll through if they don't see any code or anything that is easily noticable without having to read through then you're screwed
